repos:
  - repo: https://github.com/pycqa/isort
    rev: 6.1.0
    hooks:
      - id: isort
    
  - repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
    - id: black
      language_version: python3.13

  - repo: local
    hooks:
      - id: commitizen-check
        name: commitizen-check
        entry: scripts/check-commit-msg.sh
        language: script
        stages: [commit-msg]

      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [python]
        args: [--config-file=mypy.ini]
        files: ^(user|utils)/.*\.py$

      - id: check-schema
        name: check-schema
        entry: python manage.py check_schema
        language: system
        pass_filenames: false
        files: (views|serializers|urls)/.*\.py$

  