repos:
  - repo: https://github.com/pycqa/isort
    rev: 6.1.0
    hooks:
      - id: isort
    
  - repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
    - id: black
      language_version: python3.13

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [python]
        args: [--config-file=mypy.ini]
        files: ^(user|utils)/.*\.py$

  