[tool.black]
line-length = 200

[tool.isort]
profile = "black"
line_length = 200
force_sort_within_sections = true
sections = "FUTURE,STDLIB,DJANGO,THIRDPARTY,FIRSTPARTY,LOCALFOLDER"
known_django = ["django"]
skip = ["__init__.py", "migrations", "settings.py", "wsgi.py", "asgi.py", "venv", "env"]