# Generated by Django 5.1.7 on 2025-03-16 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="deactivated_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="비활성화일시"),
        ),
        migrations.AlterField(
            model_name="user",
            name="registered_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="가입일시"),
        ),
    ]
